import logging


LOG_LEVEL = logging.DEBUG
DB_LOG_LEVEL = logging.WARN

PYRAMID_RELOAD_TEMPLATES = True
PYRAMID_DEBUG_AUTHORIZATION = True
PYRAMID_DEBUG_NOTFOUND = True
PYRAMID_DEBUG_ROUTEMATCH = True
